### PR TITLE
0.7.3 (Fix server crash bug)

### PR DESCRIPTION
**Pull request by PTOM76**

### CODE REVIEW

**Comment by AlexIIL** [comment]
I don't really understand what this is meant to fix - can you upload a crash report for the server crash bug?

**Comment by PTOM76** [comment]
Oops, excuse me. I will send you a log.
https://pastebin.com/ZMpcURWB

**Comment by AlexIIL** [comment]
Thanks! In which case I think this is because I missed a few `@Environment(EnvType.CLIENT)` on some particle spawning methods, so I'll push that soon.

**Comment by PTOM76** [comment]
Thank you as well.

**Comment by AlexIIL** [comment]
Sorry for the delay, I've pushed [`0.7.3-pre.1`](https://alexiil.uk/maven/alexiil/mc/lib/libmultipart-all/0.7.3-pre.1/libmultipart-all-0.7.3-pre.1.jar) which should fix the crash?

**Comment by PTOM76** [comment]
Now the server no longer crashes. So thank you.

**Pull request closed without merging**
